delivery/ext/db/models.py
from delivery.ext.db import db

# To understand what is happening here:
# We have 7 tables (Category, Store, Items, Order, Order_Items, Checkout and Address),
# with each one containing it's attributes (columns).

### User table is alocate in the auth directory for best management.

# primary_key=True to set this column as the table's primary key. 

# unique=True do not allow duplicate values in this column.

# ForeignKey represents a relationship between two tables (one-to-many relationship),
# db.relationship() represents the object-oriented view of that realtionship
# Example: the primary key in Category will work as the "one" side, we will have an id for each category
# and in Store the db.relationship() will work as the "many" side,
# so if you look in the category_id there will be many stores for each id
# but in a Store there will be only one category_id that represents the store.




class Category(db.Model):
    __tablename__ = "category"
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.Unicode, unique=True)
    on_menu = db.Column("on_menu", db.Boolean)


class Store(db.Model):
    __tablename__ = "store"
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.Unicode)
    user_id = db.Column("user_id", db.Integer, db.ForeignKey("user.id"))
    category_id = db.Column(
        "category_id", db.Integer, db.ForeignKey("category.id")
    )
    activity = db.Column("activity", db.Boolean)

    user = db.relationship("User", foreign_keys=user_id)
    category = db.relationship("Category", foreign_keys=category_id)


class Items(db.Model):
    __tablename__ = "items"
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.Unicode)
    image = db.Column("image", db.Unicode)
    price = db.Column("price", db.Numeric)
    store_id = db.Column("store_id", db.Integer, db.ForeignKey("store.id"))
    available = db.Column("available", db.Boolean)

    store = db.relationship("Store", foreign_keys=store_id)


class Order(db.Model):
    __tablename__ = "order"
    id = db.Column("id", db.Integer, primary_key=True)
    created_at = db.Column("created_at", db.DateTime)
    completed = db.Column("completed", db.Boolean)
    user_id = db.Column("user_id", db.Integer, db.ForeignKey("user.id"))
    store_id = db.Column("store_id", db.Integer, db.ForeignKey("store.id"))
    address_id = db.Column(
        "address_id", db.Integer, db.ForeignKey("address.id")
    )

    user = db.relationship("User", foreign_keys=user_id)
    store = db.relationship("Store", foreign_keys=store_id)
    address = db.relationship("Address", foreign_keys=address_id)


class OrderItems(db.Model):
    __tablename__ = "order_items"
    id = db.Column("id", db.Integer, primary_key=True)
    order_id = db.Column("order_id", db.Integer, db.ForeignKey("order.id"))
    items_id = db.Column("items_id", db.Integer, db.ForeignKey("items.id"))
    quant = db.Column("quant", db.Integer)

    order = db.relationship("Order", foreign_keys=order_id)
    items = db.relationship("Items", foreign_keys=items_id)


class Checkout(db.Model):
    __tablename__ = "check_out"
    id = db.Column("id", db.Integer, primary_key=True)
    payment = db.Column("payment", db.Unicode)
    total = db.Column("total", db.Numeric)
    created_at = db.Column("created_at", db.DateTime)
    completed = db.Column("completed", db.Boolean)
    order_id = db.Column("order_id", db.Integer, db.ForeignKey("order.id"))

    order = db.relationship("Order", foreign_keys=order_id)


class Address(db.Model):
    __tablename__ = "address"
    id = db.Column("id", db.Integer, primary_key=True)
    zip = db.Column("zip", db.Unicode)
    country = db.Column("country", db.Unicode)
    address = db.Column("address", db.Unicode)
    user_id = db.Column("user_id", db.Integer, db.ForeignKey("user.id"))

    user = db.relationship("User", foreign_keys=user_id)

delivery/app.py
from flask import Flask
from delivery.ext import config


def create_app():
    app = Flask(__name__)
    config.init_app(app)
    return app

delivery/ext/__init__.py
from delivery.ext.site.main import bp


def init_app(app):
    app.register_blueprint(bp)

delivery/ext/admin/__init__.py
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from delivery.ext.db import db
from delivery.ext.db.models import Category


admin = Admin()


def init_app(app):
    admin.name = app.config.get("ADMIN_NAME", "DeliveryProject")
    admin.template_mode = app.config.get("ADMIN_TEMPLATE_MODE", "bootstrap2")
    admin.init_app(app)

    admin.add_view(ModelView(Category, db.session))

delivery/ext/cli/__init__.py
import click
from delivery.ext.db import db
from delivery.ext.auth.models import User
from delivery.ext.db import models


def init_app(app):

    @app.cli.command()
    def create_db():
        db.create_all()

    @app.cli.command()
    @click.option("--email", "-e")
    @click.option("--passwd", "-p")
    @click.option("--admin", "-a", is_flag=True, default=False)
    def add_user(email, passwd, admin):
        user = User(
            email=email,
            passwd=passwd,
            admin=admin
        )
        db.session.add(user)
        db.session.commit()

        click.echo(f"User {email} sucessfully created ")


    @app.cli.command()
    def show_orders():
        click.echo("order list")

delivery/ext/config/__init__.py
from dynaconf import FlaskDynaconf


def init_app(app):
    FlaskDynaconf(app)
    app.config.load_extensions("EXTENSIONS")

delivery/ext/db/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def init_app(app):
    db.init_app(app)
    

delivery/ext/site/__init__.py
from delivery.ext.site.main import bp


def init_app(app):
    app.register_blueprint(bp)

delivery/ext/site/controllers.py
def get_all_active_stores():
    """Get all store"""

delivery/ext/site/main.py
from flask import render_template, current_app, Blueprint, redirect
from delivery.ext.auth.form import UserForm
from delivery.ext.auth.controller import create_user


bp = Blueprint("site", __name__)


@bp.route("/")
def index():
    return render_template("index.html")

@bp.route("/about")
def about():
    return render_template("about.html")

@bp.route("/registration", methods=["GET", "POST"])
def registration():
    form = UserForm()
    if form.validate_on_submit():
        create_user(
            email=form.email.data,
            passwd=form.password.data
        )
        
        
        # forçar login
        return redirect("/")

    return render_template("userform.html", form=form)

@bp.route("/restaurants")
def restaurants():
    return render_template("restaurants.html")

@bp.route("/categories")
def categories():
    return render_template("categories.html")

delivery/ext/toolbar/__init__.py
from flask_debugtoolbar import DebugToolbarExtension


def init_app(app):
    DebugToolbarExtension(app)

delivery/templates/about.html
{% extends "base.html"%}

delivery/templates/base.html
{% block head %}
<body>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title> Delivery Project</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
{% endblock head %}

{% block nav %}
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>
    
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        </a>
    </div>
    
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
        <a class="navbar-item" href="/">
            Home
        </a>
    
        <a class="navbar-item" href="{{ url_for('site.restaurants') }}">
            Restaurants
        </a>

        <a class="navbar-item" href="{{ url_for('site.categories') }}">
            Categories
        </a>
    
        <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
            More
            </a>
    
            <div class="navbar-dropdown">
            <a class="navbar-item">
                About us
            </a>
            <a class="navbar-item">
                Contact
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
                Report an issue
            </a>
            </div>
        </div>
        </div>
    
        <div class="navbar-end">
        <div class="navbar-item">
            <div class="buttons">
            <a class="button is-primary" href="{{url_for('site.registration')}}">
                <strong>Sign up</strong>
            </a>
            <a class="button is-light">
                Log in
            </a>
            </div>
        </div>
        </div>
    </div>
    </nav>
{% endblock nav %}

{% block title %} {% endblock title %}

<section class="section">
    <div class="container"> 

        {% block main %} {% endblock main %}

{% block footer %}
<footer class="footer">
<div class="content has-text-centered">
    <p>
    <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
    <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
    is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
</div>
</footer>
{% endblock footer %}
</body>

delivery/templates/categories.html
{% extends "base.html" %}

delivery/templates/index.html
{% extends "base.html" %}
{% import "macros/rest_list.html" as rest_list %}

{% block title %}
<section class="hero is-info">
    <div class="hero-body">
        <p class="title">
        Delivery Service
        </p>
        <p class="subtitle">
        Brings you food everywhere.
        </p>
    </div>
</section>
{% endblock title %}

<section class="section">
    <div class="container"> 

{% block main %}
<div class="columns">
    {{ rest_list.cards([1, 2, 3 ,4]) }}
</div>
{% endblock main %}

delivery/templates/macros/rest_list.html
{% macro cards(items) %}

    {% for item in items %}
    <div class="column">
    <div class="card">
    <div class="card-image">
    <figure class="image is-4by3">
    <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
    </figure>
    </div>
    <div class="card-content">
    <div class="media">
    <div class="media-left">
    <figure class="image is-48x48">
    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
    </figure>
    </div>
    <div class="media-content">
    <p class="title is-4">John Smith</p>
    <p class="subtitle is-6">@johnsmith</p>
    </div>
    </div>

    <div class="content">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Phasellus nec iaculis mauris. <a>@bulmaio</a>.
    <a href="#">#css</a> <a href="#">#responsive</a>
    <br>
    <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
    </div>
    </div>
    </div>
    </div>
    {% endfor %}

{% endmacro %}

delivery/templates/restaurants.html
{% extends "base.html" %}
{% import "macros/rest_list.html" as rest_list %}

{% block title %}
<section class="hero is-info">
    <div class="hero-body">
        <p class="title">
        Delivery Service
        </p>
        <p class="subtitle">
        Brings you food everywhere.
        </p>
    </div>
</section>
{% endblock title %}

{% block main %}
<div class="columns">
    {{ rest_list.cards([1, 2, 3 ,4]) }}
</div>
{% endblock main %}

delivery/templates/userform.html
{% extends "base.html" %}

{% block title %}
<section class="hero is-info">
    <div class="hero-body">
        <p class="title">
        Delivery Service
        </p>
        <p class="subtitle">
        Brings you food everywhere.
        </p>
    </div>
</section>
{% endblock title %}

<section class="section">
    <div class="container">
        <h1>Sign up in our site!</h1> 

{% block main %}
<form action="{{url_for('site.registration')}}" method="POST" enctype="multipart/form-data">
    {{form.csrf_token}}

    {{form.email.label}}<br>
    {{form.email(size=20)}}<br>

    {{form.password.label}}<br>
    {{form.password(size=20)}}<br>

    {{form.foto.label}}<br>
    {{form.foto}}<br>

    <input type="Submit" value="Sign up!" />
</form>
{% endblock main %}